name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.2"
        env:
          GITHUB_TOKEN: "${{ secrets.MY_TOKEN }}"
          MERGE_LABELS: "automerge"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_REMOVE_LABELS: "automerge"
          MERGE_METHOD: "squash"